#259 [feature] HomeFragment Image Loading Optimization
Daily-DAYO/DAYO_Android pull request #260
Opened 2022-06-18 18:12 UTC by DongJun-H

## 내용
- Glide 오류에 대한 디버깅 및 GlideModule 도입
- HomePagerStateAdapter에서 발생한 오류 디버깅
- HomeFragment에 대한 DAYOPICK 과 NEW에서 공통으로 사용하던 부분 제거 및 생성
- HomeFragment에서의 이미지 로딩 최적화
- HomeFragment에서의 이미지 로딩 완료 이전 스켈레톤 UI 구현

## 작업 사항
### Build.gradle
	- GlideApp 사용을 위한 Compiler 추가
	- Shimmer 사용을 위한 라이브러리 추가
### Color
	- Alpha 0.3을 적용한 Gray3 추가
### GlideModule
	- You cannot start a load for a destroyed activity 오류 메시지에 대한 디버깅
	- 이를 위해 GlideModule 파일 생성 및 Glide 사용시 활용
	- adapter에서 Glide 사용 시, Constructor에 requestManager를 받아 이를 이용해 이미지 로드
### HomeFragment
	- Layout 일부 자잘한 수정
	- 관련 기능 구현 코드 Refactoring
	- Swipe을 통한 Tab간 이동 기능 Disable
	- 최초 HomeFragment create되는 경우에만 homeViewModel을 통해 PostList를 받아오도록 수정 및 Create되는 경우에는 무조건 전체 카테고리를 보도록 수정
	- PagerStateAdapter에 대한 refreshFragment 관련 코드에서 notify 관련 함수 오류 경고 메시지에 따른 디버깅

### PostListFragment (DAYOPICK, NEW 공통)
	- Layout에 ShimmerFrameLayout 추가하여 이미지 로딩 시 화면 구현
		- 관련 item_main_post_shimmer.xml Layout 구현 및 사용
	- Layout 수정을 통해 전체 이미지를 한번에 로딩하는 것이 아닌 보이는 부분만 이미지가 로딩될 수 있도록 구현
	- 카테고리 선택 후, BottomNavigation으로 다른 Fragment으로 이동 후, 다시 HomeFragment으로 돌아왔을 때, 카테고리 선택이 초기화되어져 있는 것으로 보이는 Bug Fix
	- 홈 화면 페이지를 로딩하거나 카테고리 변경을 하는 경우 등의 상황에서 6개 이내의 이미지가 로딩된 후 게시글 썸네일을 볼 수 있도록 처리
		- 초기 6개 이미지에 대한 서버와의 통신 완료 시, 덮어씌워져 있던 Shimmer Layout은 View.GONE 처리
		- 카테고리에 6개 이내의 이미지만 존재하는 경우에는 모두 로딩한 뒤에 Shimmer Layout을 GONE 처리
	- 카테고리 변경 시마다, Shimmer Layout이 보이도록 처리하여, 로딩 중에는 카테고리를 변경할 수 없도록 구현
		- 초기 이미지가 로딩되지 않은 상태에서 스크롤을 가능하게 하는 등의 동작을 가능토록 하는 경우, 메모리 과다 사용 방지

### Post adapter(DAYOPICK, NEW 공통)
	- 현재 보이는 이미지 이외에 용이한 이미지 로딩을 위하여 이어지는 하단의 6개의 이미지가 미리 로딩할 수 있도록 Adapter에서 preload 코드 추가
	- Glide.with~ 대신 requestManager을 도입하여 glide를 사용하여 이미지 로딩
	- 이미지가 서버에서 불러와진 후, 화면에 보이는 사이에 보여지는 placeholder 이미지 기존 DAYO Grayscale 이미지에서 Shimmer Layout에서 사용되는 배경색과 동일한 단색 이미지로 변경
	- preload된 이미지가 있는 경우에는 preload된 이미지를 사용하도록 변경
	- getItemViewType Function을 Override하여 DayoPick 게시글 카테고리 변경 시 랭킹 표시에 오류가 있었던 Bug Fix (DayoPickAdapter 만)
	- HomeDayoPickAdapter과 HomeNewAdapter을 각각 Fragment에 맞게 분리하여 사용하도록 구현

### HomeViewModel
	- HomeFragment에 포함될 Contents가 초기에 로딩되어있는 지 판단하는 구분하는 variable 추가
		- isInitLoadingDAYOPICK, isInitLoadingNew
	- 기존에 DAYO PICK과 NEW가 공유하고 있던 currentCategory variable 분리
	- 기존에 DAYO PICK과 NEW가 공유하고 있던 postList variable 분리
	- coroutine 사용 코드에 대한 Dispatcher 명시

### item_main_post
	- 각각의 썸네일에 대해서도 shimmer 적용이 가능하도록 Shimmer Layout 추가

### Post DataClass
	- Shimmer Layout 도입에 따른 미리 이미지를 로딩함에 따라 preLoadThumbnail, preLoadUserImg 추가
## 참고
- resolved: #259

2022-06-20 19:56 UTC, gemiJ requested changes

2022-06-20 19:56 UTC, gemiJ commented on app/src/main/java/com/daily/dayo/presentation/viewmodel/HomeViewModel.kt
> +    lateinit var currentNewCategory : Category
이 부분에서 간헐적으로 lateinit이 초기화 되기 전 사용되는 에러가 발생하는 것 같습니다!
HomeFragment에서 requestDayoPickPostList(), requestNewPostList()시 초기화되지 않은 상태에서 if문에 사용될 수 있을 것 같네요

2022-06-20 19:59 UTC, gemiJ commented
Glide의 requestManager에 대해 처음 알게되었어요! 
대대적인 수정하느라 고생하셨습니다 👍 👍  😄

2022-06-27 13:51 UTC, DongJun-H commented on app/src/main/java/com/daily/dayo/presentation/viewmodel/HomeViewModel.kt
> +    lateinit var currentNewCategory : Category
각각 request하기전에 초기화 하도록 수정하였습니다

2022-06-27 14:54 UTC, gemiJ approved these changes

2022-06-28 12:48 UTC, merged